### ISSUE TITLE
hello that's new issues

### ISSUE THREAD

**Issue by Anubi5x0** [reivhax/Chimay-Red-tiny#2]
┌─[anubi5@parrot]─[~/Downloads/Chimay-Red-tiny-master]
└──╼ $python chimayred.py 192.168.0.1
Traceback (most recent call last):
  File "chimayred.py", line 151, in <module>
    router=Vuln(sys.argv[1],sys.argv[2] if len(sys.argv) == 3 else 80)
  File "chimayred.py", line 28, in __init__
    self.vulnerable=self.check_vulnerable()
  File "chimayred.py", line 45, in check_vulnerable
    if int(router_version)>63840:
ValueError: invalid literal for int() with base 10: 'meta http-equiv="Content-Type" content="text/html; charset=utf-8"><title></title></head><frameset rows="0,*" border=0 frameborder=no framespacing=0><frame src="spacehtm" name="space" scrolling="no" bo'

**Comment by xaviermilgo** [comment]
Can you please confirm that the target 192.168.0.1 is a mikrotik router running a web service?

**Comment by xaviermilgo** [comment]
What Mikrotik version is running on the router?

**Comment by Anubi5x0** [comment]
yes it's 192.168.01 
my RouterOS v5.25
